import { cardsType, menuDataType } from "@util/types";

export const menuData: menuDataType[] = [
  {
    menu: "※ゴールの守護神",
    card1: "a.7.セットプレー",
    card2: "c.5.アジリティ",
    card3: "/",
    kick: 0,
    speed: 0,
    energy: 0,
    technique: 2,
    physical: 0,
    jump: 10,
    mental: 4,
    Fatigue: 80,
    defense: 2,
    offense: 0,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "※スーパーセーブ",
    card1: "b.7.ヘディング",
    card2: "d.2.座禅",
    card3: "/",
    kick: 0,
    speed: 0,
    energy: 4,
    technique: 0,
    physical: 0,
    jump: 8,
    mental: 8,
    Fatigue: 73,
    defense: 2,
    offense: 0,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "※鬼神のセーブ",
    card1: "c.6.エアロビクス",
    card2: "d.2.座禅",
    card3: "d.4.PK練習",
    kick: 0,
    speed: 0,
    energy: 4,
    technique: 8,
    physical: 0,
    jump: 0,
    mental: 10,
    Fatigue: 75,
    defense: 2,
    offense: 0,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "※掟破りの攻撃参加",
    card1: "a.7.セットプレー",
    card2: "c.1.ランニング",
    card3: "d.b.カラオケ",
    kick: 12,
    speed: 0,
    energy: 8,
    technique: 0,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 60,
    defense: 0,
    offense: 3,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "△アフターチャージ",
    card1: "a.3.プレス",
    card2: "c.3.キック",
    card3: "d.b.カラオケ",
    kick: 12,
    speed: 0,
    energy: 0,
    technique: -2,
    physical: 0,
    jump: 0,
    mental: -2,
    Fatigue: 75,
    defense: 0,
    offense: 0,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "△オーバートレーニング",
    card1: "b.6.スライディング",
    card2: "c.1.ランニング",
    card3: "c.2.ウェイト",
    kick: -1,
    speed: 0,
    energy: -4,
    technique: 0,
    physical: 24,
    jump: 0,
    mental: -2,
    Fatigue: 145,
    defense: 0,
    offense: 0,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "△キーパーチャージ",
    card1: "a.6.ラインコントロール",
    card2: "b.3.シュート",
    card3: "b.6.スライディング",
    kick: -2,
    speed: 0,
    energy: 0,
    technique: 8,
    physical: 0,
    jump: -2,
    mental: -2,
    Fatigue: 110,
    defense: 0,
    offense: 0,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "△シミュレーション",
    card1: "b.3.シュート",
    card2: "c.5.アジリティ",
    card3: "d.6.イメージトレーニング",
    kick: 0,
    speed: 24,
    energy: -4,
    technique: 0,
    physical: 0,
    jump: 0,
    mental: -4,
    Fatigue: 120,
    defense: 0,
    offense: 0,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "△現実逃避",
    card1: "d.8.温泉",
    card2: "d.a.カルチョビット",
    card3: "d.b.カラオケ",
    kick: 0,
    speed: 0,
    energy: 0,
    technique: 8,
    physical: -4,
    jump: 0,
    mental: -2,
    Fatigue: 30,
    defense: 0,
    offense: 0,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "△神の手",
    card1: "a.3.プレス",
    card2: "b.3.シュート",
    card3: "b.7.ヘディング",
    kick: 12,
    speed: 0,
    energy: 0,
    technique: -2,
    physical: 0,
    jump: 0,
    mental: -4,
    Fatigue: 120,
    defense: 0,
    offense: 0,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "△遅延行為",
    card1: "b.2.プレースキック",
    card2: "c.1.ランニング",
    card3: "d.8.温泉",
    kick: 0,
    speed: -4,
    energy: 24,
    technique: 0,
    physical: 0,
    jump: -2,
    mental: -2,
    Fatigue: 100,
    defense: 0,
    offense: 0,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "２次攻撃",
    card1: "a.3.プレス",
    card2: "c.4.ダッシュ",
    card3: "/",
    kick: 4,
    speed: 4,
    energy: 0,
    technique: 2,
    physical: 0,
    jump: 4,
    mental: 0,
    Fatigue: 93,
    defense: 3,
    offense: 1,
    type1: "ダイナモ(5)",
    type2: "",
    type3: "",
  },
  {
    menu: "FKマイスター",
    card1: "a.7.セットプレー",
    card2: "b.2.プレースキック",
    card3: "d.4.PK練習",
    kick: 12,
    speed: 0,
    energy: 0,
    technique: 0,
    physical: 0,
    jump: 0,
    mental: 8,
    Fatigue: 70,
    defense: 0,
    offense: 2,
    type1: "アタッカー(4)",
    type2: "",
    type3: "",
  },
  {
    menu: "アイコンタクト",
    card1: "a.5.ミニゲーム",
    card2: "d.7.ミーティング",
    card3: "/",
    kick: 1,
    speed: 2,
    energy: 2,
    technique: 2,
    physical: 0,
    jump: 0,
    mental: 4,
    Fatigue: 46,
    defense: 3,
    offense: 0,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "アグレッシブボランチ",
    card1: "a.3.プレス",
    card2: "b.1.ドリブル",
    card3: "b.6.スライディング",
    kick: 3,
    speed: 6,
    energy: 6,
    technique: 4,
    physical: 6,
    jump: 0,
    mental: 0,
    Fatigue: 120,
    defense: 6,
    offense: 0,
    type1: "オールラウンド(5)",
    type2: "ストッパー(6)",
    type3: "マンマーカー(8)",
  },
  {
    menu: "アクロバット",
    card1: "a.4.カウンター",
    card2: "c.6.エアロビクス",
    card3: "c.7.ストレッチ",
    kick: 0,
    speed: 6,
    energy: 5,
    technique: 2,
    physical: 6,
    jump: 2,
    mental: 0,
    Fatigue: 120,
    defense: 2,
    offense: 3,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "イリュージョンステップ",
    card1: "c.4.ダッシュ",
    card2: "c.5.アジリティ",
    card3: "d.1.アロマテラピー",
    kick: 0,
    speed: 10,
    energy: 0,
    technique: 6,
    physical: 0,
    jump: 0,
    mental: 4,
    Fatigue: 100,
    defense: 2,
    offense: 2,
    type1: "アタッカー(6)",
    type2: "",
    type3: "",
  },
  {
    menu: "インターセプト",
    card1: "b.6.スライディング",
    card2: "d.6.イメージトレーニング",
    card3: "/",
    kick: 0,
    speed: 0,
    energy: 0,
    technique: 4,
    physical: 6,
    jump: 0,
    mental: 4,
    Fatigue: 93,
    defense: 3,
    offense: 0,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ウルトラリラックス",
    card1: "c.7.ストレッチ",
    card2: "d.1.アロマテラピー",
    card3: "d.8.温泉",
    kick: 0,
    speed: 0,
    energy: 6,
    technique: 2,
    physical: 10,
    jump: 0,
    mental: 8,
    Fatigue: 65,
    defense: 1,
    offense: 1,
    type1: "スイーパー(7)",
    type2: "バックアップ(8)",
    type3: "",
  },
  {
    menu: "エースキラー",
    card1: "a.2.マンツーマン",
    card2: "b.6.スライディング",
    card3: "c.4.ダッシュ",
    kick: 0,
    speed: 12,
    energy: 6,
    technique: 2,
    physical: 10,
    jump: 0,
    mental: 0,
    Fatigue: 120,
    defense: 6,
    offense: 0,
    type1: "ストッパー(4)",
    type2: "マンマーカー(6)",
    type3: "",
  },
  {
    menu: "オーバーラップ",
    card1: "a.4.カウンター",
    card2: "c.1.ランニング",
    card3: "/",
    kick: 0,
    speed: 6,
    energy: 12,
    technique: 0,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 86,
    defense: 1,
    offense: 2,
    type1: "ダイナモ(3)",
    type2: "",
    type3: "",
  },
  {
    menu: "オフサイドトラップ",
    card1: "a.6.ラインコントロール",
    card2: "d.7.ミーティング",
    card3: "/",
    kick: 0,
    speed: 0,
    energy: 4,
    technique: 1,
    physical: 0,
    jump: 0,
    mental: 8,
    Fatigue: 20,
    defense: 4,
    offense: 0,
    type1: "バックアップ(7)",
    type2: "",
    type3: "",
  },
  {
    menu: "オプションプレー",
    card1: "a.7.セットプレー",
    card2: "d.6.イメージトレーニング",
    card3: "/",
    kick: 3,
    speed: 0,
    energy: 0,
    technique: 2,
    physical: 0,
    jump: 4,
    mental: 2,
    Fatigue: 40,
    defense: 0,
    offense: 1,
    type1: "レジスタ(6)",
    type2: "",
    type3: "",
  },
  {
    menu: "カテナチオ",
    card1: "a.1.ビデオ研究",
    card2: "a.2.マンツーマン",
    card3: "a.6.ラインコントロール",
    kick: 2,
    speed: 4,
    energy: 6,
    technique: 2,
    physical: 6,
    jump: 0,
    mental: 0,
    Fatigue: 35,
    defense: 5,
    offense: 0,
    type1: "バックアップ(4)",
    type2: "",
    type3: "",
  },
  {
    menu: "カバーリング",
    card1: "a.6.ラインコントロール",
    card2: "c.4.ダッシュ",
    card3: "/",
    kick: 2,
    speed: 6,
    energy: 4,
    technique: 0,
    physical: 0,
    jump: 6,
    mental: 0,
    Fatigue: 80,
    defense: 4,
    offense: 0,
    type1: "バックアップ(6)",
    type2: "スイーパー(11)",
    type3: "",
  },
  {
    menu: "カミソリドリブル",
    card1: "b.1.ドリブル",
    card2: "d.6.イメージトレーニング",
    card3: "/",
    kick: 0,
    speed: 6,
    energy: 0,
    technique: 6,
    physical: 0,
    jump: 0,
    mental: 4,
    Fatigue: 93,
    defense: 0,
    offense: 2,
    type1: "アタッカー(6)",
    type2: "",
    type3: "",
  },
  {
    menu: "キャプテンシー",
    card1: "c.1.ランニング",
    card2: "d.7.ミーティング",
    card3: "/",
    kick: 0,
    speed: 0,
    energy: 10,
    technique: 0,
    physical: 0,
    jump: 0,
    mental: 10,
    Fatigue: 66,
    defense: 2,
    offense: 1,
    type1: "ダイナモ(7)",
    type2: "",
    type3: "",
  },
  {
    menu: "キラーパス",
    card1: "b.4.パス",
    card2: "c.3.キック",
    card3: "d.1.アロマテラピー",
    kick: 2,
    speed: 5,
    energy: 0,
    technique: 5,
    physical: 5,
    jump: 0,
    mental: 3,
    Fatigue: 100,
    defense: 0,
    offense: 4,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "クライフターン",
    card1: "c.5.アジリティ",
    card2: "c.6.エアロビクス",
    card3: "/",
    kick: 0,
    speed: 6,
    energy: 0,
    technique: 6,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 133,
    defense: 2,
    offense: 2,
    type1: "ダイナモ(7)",
    type2: "",
    type3: "",
  },
  {
    menu: "ゲームメーカー",
    card1: "b.4.パス",
    card2: "d.a.カルチョビット",
    card3: "/",
    kick: 0,
    speed: 6,
    energy: 0,
    technique: 3,
    physical: 0,
    jump: 0,
    mental: 6,
    Fatigue: 80,
    defense: 0,
    offense: 2,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ゴールの嗅覚",
    card1: "d.1.アロマテラピー",
    card2: "d.2.座禅",
    card3: "d.6.イメージトレーニング",
    kick: 3,
    speed: 4,
    energy: 0,
    technique: 3,
    physical: 0,
    jump: 3,
    mental: 4,
    Fatigue: 25,
    defense: 0,
    offense: 1,
    type1: "アタッカー(4)",
    type2: "",
    type3: "",
  },
  {
    menu: "コンパクトフィールド",
    card1: "a.3.プレス",
    card2: "a.6.ラインコントロール",
    card3: "/",
    kick: 0,
    speed: 4,
    energy: 4,
    technique: 0,
    physical: 0,
    jump: 0,
    mental: 4,
    Fatigue: 40,
    defense: 3,
    offense: 1,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "サイドアタック",
    card1: "b.1.ドリブル",
    card2: "c.1.ランニング",
    card3: "/",
    kick: 0,
    speed: 10,
    energy: 10,
    technique: 0,
    physical: 2,
    jump: 0,
    mental: 4,
    Fatigue: 126,
    defense: 0,
    offense: 4,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "サイドチェンジ",
    card1: "a.1.ビデオ研究",
    card2: "b.2.プレースキック",
    card3: "/",
    kick: 4,
    speed: 0,
    energy: 6,
    technique: 0,
    physical: 0,
    jump: 0,
    mental: 6,
    Fatigue: 60,
    defense: 1,
    offense: 1,
    type1: "レジスタ(10)",
    type2: "",
    type3: "",
  },
  {
    menu: "サンバステップ",
    card1: "a.1.ビデオ研究",
    card2: "b.6.スライディング",
    card3: "c.5.アジリティ",
    kick: 2,
    speed: 3,
    energy: 0,
    technique: 3,
    physical: 3,
    jump: 4,
    mental: 1,
    Fatigue: 105,
    defense: 3,
    offense: 1,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "シザーズフェイント",
    card1: "c.5.アジリティ",
    card2: "d.3.サイン会",
    card3: "/",
    kick: 0,
    speed: 4,
    energy: 0,
    technique: 3,
    physical: 0,
    jump: 0,
    mental: 6,
    Fatigue: 73,
    defense: 1,
    offense: 1,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "シャドーストライカー",
    card1: "a.1.ビデオ研究",
    card2: "b.3.シュート",
    card3: "d.8.温泉",
    kick: 7,
    speed: 5,
    energy: 0,
    technique: 2,
    physical: 0,
    jump: 0,
    mental: 2,
    Fatigue: 70,
    defense: 0,
    offense: 2,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "シャンパンサッカー",
    card1: "a.5.ミニゲーム",
    card2: "b.4.パス",
    card3: "c.5.アジリティ",
    kick: 3,
    speed: 10,
    energy: 0,
    technique: 6,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 130,
    defense: 2,
    offense: 4,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "シュートコースカット",
    card1: "b.6.スライディング",
    card2: "c.7.ストレッチ",
    card3: "/",
    kick: 0,
    speed: 6,
    energy: 0,
    technique: 2,
    physical: 8,
    jump: 0,
    mental: 6,
    Fatigue: 133,
    defense: 4,
    offense: 0,
    type1: "バックアップ(3)",
    type2: "",
    type3: "",
  },
  {
    menu: "スーパーサブ",
    card1: "c.4.ダッシュ",
    card2: "d.4.PK練習",
    card3: "/",
    kick: 3,
    speed: 8,
    energy: 0,
    technique: 0,
    physical: 0,
    jump: 6,
    mental: 0,
    Fatigue: 93,
    defense: 1,
    offense: 2,
    type1: "レジスタ(6)",
    type2: "",
    type3: "",
  },
  {
    menu: "すっぽんマーク",
    card1: "a.2.マンツーマン",
    card2: "c.1.ランニング",
    card3: "/",
    kick: 0,
    speed: 4,
    energy: 10,
    technique: 0,
    physical: 4,
    jump: 0,
    mental: 4,
    Fatigue: 86,
    defense: 4,
    offense: 0,
    type1: "オールラウンド(4)",
    type2: "",
    type3: "",
  },
  {
    menu: "スティールハート",
    card1: "d.4.PK練習",
    card2: "d.5.合気道",
    card3: "/",
    kick: 3,
    speed: 0,
    energy: 0,
    technique: 1,
    physical: 0,
    jump: 0,
    mental: 12,
    Fatigue: 40,
    defense: 1,
    offense: 1,
    type1: "バックアップ(9)",
    type2: "",
    type3: "",
  },
  {
    menu: "スペースのケア",
    card1: "a.5.ミニゲーム",
    card2: "c.6.エアロビクス",
    card3: "/",
    kick: 0,
    speed: 0,
    energy: 6,
    technique: 4,
    physical: 4,
    jump: 0,
    mental: 0,
    Fatigue: 106,
    defense: 4,
    offense: 0,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "スライディングヘッド",
    card1: "b.6.スライディング",
    card2: "b.7.ヘディング",
    card3: "d.8.温泉",
    kick: 3,
    speed: 0,
    energy: 0,
    technique: 2,
    physical: 6,
    jump: 6,
    mental: 6,
    Fatigue: 115,
    defense: 2,
    offense: 2,
    type1: "スイーパー(5)",
    type2: "",
    type3: "",
  },
  {
    menu: "ターゲットマン",
    card1: "a.4.カウンター",
    card2: "b.7.ヘディング",
    card3: "c.2.ウェイト",
    kick: 5,
    speed: 5,
    energy: 5,
    technique: 2,
    physical: 0,
    jump: 5,
    mental: 0,
    Fatigue: 120,
    defense: 2,
    offense: 3,
    type1: "レジスタ(10)",
    type2: "",
    type3: "",
  },
  {
    menu: "ダイアゴナルラン",
    card1: "c.1.ランニング",
    card2: "d.6.イメージトレーニング",
    card3: "/",
    kick: 0,
    speed: 6,
    energy: 8,
    technique: 1,
    physical: 0,
    jump: 0,
    mental: 6,
    Fatigue: 86,
    defense: 0,
    offense: 2,
    type1: "レジスタ(3)",
    type2: "",
    type3: "",
  },
  {
    menu: "ダイレクトパス",
    card1: "b.4.パス",
    card2: "b.5.リフティング",
    card3: "/",
    kick: 0,
    speed: 7,
    energy: 0,
    technique: 6,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 133,
    defense: 1,
    offense: 3,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "タフネスダイナモ",
    card1: "a.3.プレス",
    card2: "c.1.ランニング",
    card3: "c.5.アジリティ",
    kick: 0,
    speed: 10,
    energy: 14,
    technique: 5,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 115,
    defense: 4,
    offense: 2,
    type1: "ダイナモ(4)",
    type2: "",
    type3: "",
  },
  {
    menu: "チーム愛",
    card1: "d.1.アロマテラピー",
    card2: "d.3.サイン会",
    card3: "d.7.ミーティング",
    kick: 0,
    speed: 0,
    energy: 0,
    technique: 0,
    physical: 0,
    jump: 0,
    mental: 20,
    Fatigue: 10,
    defense: 1,
    offense: 0,
    type1: "ダイナモ(3)",
    type2: "アタッカー(10)",
    type3: "",
  },
  {
    menu: "チェイシング",
    card1: "a.3.プレス",
    card2: "c.6.エアロビクス",
    card3: "/",
    kick: 0,
    speed: 6,
    energy: 8,
    technique: 0,
    physical: 6,
    jump: 0,
    mental: 0,
    Fatigue: 93,
    defense: 4,
    offense: 0,
    type1: "オールラウンド(5)",
    type2: "ストッパー(6)",
    type3: "マンマーカー(7)",
  },
  {
    menu: "トータルフットボール",
    card1: "a.6.ラインコントロール",
    card2: "b.1.ドリブル",
    card3: "d.9.ミニキャンプ",
    kick: 3,
    speed: 3,
    energy: 3,
    technique: 3,
    physical: 3,
    jump: 3,
    mental: 3,
    Fatigue: 80,
    defense: 2,
    offense: 2,
    type1: "バックアップ(9)",
    type2: "",
    type3: "",
  },
  {
    menu: "トライアングル",
    card1: "a.1.ビデオ研究",
    card2: "b.4.パス",
    card3: "/",
    kick: 1,
    speed: 6,
    energy: 0,
    technique: 3,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 73,
    defense: 2,
    offense: 0,
    type1: "ダイナモ(5)",
    type2: "アタッカー(7)",
    type3: "",
  },
  {
    menu: "ドライブシュート",
    card1: "a.4.カウンター",
    card2: "b.3.シュート",
    card3: "c.4.ダッシュ",
    kick: 9,
    speed: 10,
    energy: 0,
    technique: 0,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 120,
    defense: 0,
    offense: 5,
    type1: "レジスタ(4)",
    type2: "ストライカー(9)",
    type3: "",
  },
  {
    menu: "トリッキーフェイント",
    card1: "a.1.ビデオ研究",
    card2: "b.5.リフティング",
    card3: "/",
    kick: 2,
    speed: 4,
    energy: 0,
    technique: 4,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 73,
    defense: 1,
    offense: 1,
    type1: "レジスタ(7)",
    type2: "アタッカー(10)",
    type3: "",
  },
  {
    menu: "トリックプレイ",
    card1: "a.7.セットプレー",
    card2: "d.7.ミーティング",
    card3: "/",
    kick: 2,
    speed: 0,
    energy: 0,
    technique: 0,
    physical: 0,
    jump: 0,
    mental: 8,
    Fatigue: 20,
    defense: 1,
    offense: 1,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ドリブルシュート",
    card1: "b.1.ドリブル",
    card2: "b.3.シュート",
    card3: "/",
    kick: 6,
    speed: 6,
    energy: 0,
    technique: 3,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 133,
    defense: 0,
    offense: 4,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ナックルシュート",
    card1: "b.3.シュート",
    card2: "d.1.アロマテラピー",
    card3: "d.9.ミニキャンプ",
    kick: 6,
    speed: 0,
    energy: 0,
    technique: 3,
    physical: 0,
    jump: 0,
    mental: 6,
    Fatigue: 70,
    defense: 0,
    offense: 2,
    type1: "レジスタ(5)",
    type2: "",
    type3: "",
  },
  {
    menu: "ノールックパス",
    card1: "b.4.パス",
    card2: "c.4.ダッシュ",
    card3: "d.6.イメージトレーニング",
    kick: 0,
    speed: 6,
    energy: 0,
    technique: 6,
    physical: 0,
    jump: 0,
    mental: 8,
    Fatigue: 120,
    defense: 1,
    offense: 3,
    type1: "レジスタ(6)",
    type2: "",
    type3: "",
  },
  {
    menu: "バイシクルシュート",
    card1: "b.3.シュート",
    card2: "c.6.エアロビクス",
    card3: "d.5.合気道",
    kick: 4,
    speed: 0,
    energy: 6,
    technique: 4,
    physical: 6,
    jump: 0,
    mental: 0,
    Fatigue: 110,
    defense: 0,
    offense: 4,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ハイハイトレイン",
    card1: "a.6.ラインコントロール",
    card2: "c.7.ストレッチ",
    card3: "d.8.温泉",
    kick: 0,
    speed: 4,
    energy: 2,
    technique: 0,
    physical: 7,
    jump: 2,
    mental: 4,
    Fatigue: 75,
    defense: 3,
    offense: 1,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "バナナシュート",
    card1: "b.2.プレースキック",
    card2: "b.3.シュート",
    card3: "/",
    kick: 11,
    speed: 0,
    energy: 0,
    technique: 0,
    physical: 0,
    jump: 0,
    mental: 4,
    Fatigue: 120,
    defense: 0,
    offense: 3,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ハングリー精神",
    card1: "c.2.ウェイト",
    card2: "d.2.座禅",
    card3: "/",
    kick: 2,
    speed: 0,
    energy: 6,
    technique: 3,
    physical: 4,
    jump: 0,
    mental: 0,
    Fatigue: 73,
    defense: 1,
    offense: 1,
    type1: "ストッパー(7)",
    type2: "",
    type3: "",
  },
  {
    menu: "ピッチの監督",
    card1: "a.1.ビデオ研究",
    card2: "d.4.PK練習",
    card3: "d.7.ミーティング",
    kick: 5,
    speed: 0,
    energy: 0,
    technique: 2,
    physical: 0,
    jump: 0,
    mental: 10,
    Fatigue: 30,
    defense: 1,
    offense: 1,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ピンポイントパス",
    card1: "b.4.パス",
    card2: "d.5.合気道",
    card3: "/",
    kick: 0,
    speed: 6,
    energy: 0,
    technique: 4,
    physical: 0,
    jump: 0,
    mental: 6,
    Fatigue: 80,
    defense: 0,
    offense: 2,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ファンサービス",
    card1: "a.1.ビデオ研究",
    card2: "d.3.サイン会",
    card3: "/",
    kick: 0,
    speed: 0,
    energy: 4,
    technique: 0,
    physical: 0,
    jump: 0,
    mental: 10,
    Fatigue: 13,
    defense: 0,
    offense: 0,
    type1: "レジスタ(5)",
    type2: "",
    type3: "",
  },
  {
    menu: "ファンタジスタ",
    card1: "b.2.プレースキック",
    card2: "c.6.エアロビクス",
    card3: "d.3.サイン会",
    kick: 10,
    speed: 0,
    energy: 0,
    technique: 4,
    physical: 6,
    jump: 0,
    mental: 0,
    Fatigue: 95,
    defense: 0,
    offense: 3,
    type1: "アタッカー(3)",
    type2: "ストライカー(8)",
    type3: "",
  },
  {
    menu: "ブラインドシュート",
    card1: "a.2.マンツーマン",
    card2: "b.3.シュート",
    card3: "/",
    kick: 5,
    speed: 0,
    energy: 0,
    technique: 3,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 93,
    defense: 0,
    offense: 3,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ブラインドプレーン",
    card1: "a.7.セットプレー",
    card2: "b.5.リフティング",
    card3: "c.2.ウェイト",
    kick: 3,
    speed: 0,
    energy: 0,
    technique: 5,
    physical: 4,
    jump: 0,
    mental: 2,
    Fatigue: 110,
    defense: 2,
    offense: 3,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ヘディングシュート",
    card1: "b.7.ヘディング",
    card2: "c.5.アジリティ",
    card3: "/",
    kick: 3,
    speed: 0,
    energy: 0,
    technique: 0,
    physical: 6,
    jump: 14,
    mental: 0,
    Fatigue: 133,
    defense: 2,
    offense: 3,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ベルベットパス",
    card1: "b.4.パス",
    card2: "c.7.ストレッチ",
    card3: "/",
    kick: 0,
    speed: 10,
    energy: 0,
    technique: 4,
    physical: 4,
    jump: 0,
    mental: 4,
    Fatigue: 133,
    defense: 1,
    offense: 3,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ホーミングクロス",
    card1: "b.2.プレースキック",
    card2: "c.3.キック",
    card3: "d.9.ミニキャンプ",
    kick: 6,
    speed: 4,
    energy: 4,
    technique: 2,
    physical: 4,
    jump: 0,
    mental: 4,
    Fatigue: 110,
    defense: 1,
    offense: 2,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ボールのマジシャン",
    card1: "b.2.プレースキック",
    card2: "b.5.リフティング",
    card3: "b.7.ヘディング",
    kick: 7,
    speed: 0,
    energy: 0,
    technique: 8,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 140,
    defense: 3,
    offense: 3,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ポストプレー",
    card1: "b.4.パス",
    card2: "b.7.ヘディング",
    card3: "/",
    kick: 0,
    speed: 0,
    energy: 0,
    technique: 6,
    physical: 8,
    jump: 0,
    mental: 0,
    Fatigue: 133,
    defense: 1,
    offense: 3,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ボディバランス",
    card1: "b.5.リフティング",
    card2: "c.3.キック",
    card3: "/",
    kick: 0,
    speed: 0,
    energy: 0,
    technique: 7,
    physical: 7,
    jump: 0,
    mental: 0,
    Fatigue: 133,
    defense: 2,
    offense: 2,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ボレーシュート",
    card1: "b.3.シュート",
    card2: "c.7.ストレッチ",
    card3: "/",
    kick: 9,
    speed: 0,
    energy: 0,
    technique: 2,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 133,
    defense: 0,
    offense: 4,
    type1: "レジスタ(8)",
    type2: "",
    type3: "",
  },
  {
    menu: "ボンバーヘッド",
    card1: "a.2.マンツーマン",
    card2: "b.7.ヘディング",
    card3: "d.9.ミニキャンプ",
    kick: 5,
    speed: 0,
    energy: 4,
    technique: 0,
    physical: 0,
    jump: 12,
    mental: 6,
    Fatigue: 90,
    defense: 2,
    offense: 2,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "マークの受け渡し",
    card1: "a.2.マンツーマン",
    card2: "d.a.カルチョビット",
    card3: "/",
    kick: 0,
    speed: 0,
    energy: 4,
    technique: 2,
    physical: 2,
    jump: 0,
    mental: 4,
    Fatigue: 40,
    defense: 3,
    offense: 0,
    type1: "ストッパー(4)",
    type2: "マンマーカー(6)",
    type3: "",
  },
  {
    menu: "マグネットトラップ",
    card1: "b.5.リフティング",
    card2: "c.7.ストレッチ",
    card3: "d.6.イメージトレーニング",
    kick: 0,
    speed: 6,
    energy: 0,
    technique: 8,
    physical: 4,
    jump: 0,
    mental: 4,
    Fatigue: 120,
    defense: 2,
    offense: 2,
    type1: "レジスタ(6)",
    type2: "",
    type3: "",
  },
  {
    menu: "マジックトラップ",
    card1: "b.5.リフティング",
    card2: "d.5.合気道",
    card3: "/",
    kick: 0,
    speed: 0,
    energy: 0,
    technique: 6,
    physical: 0,
    jump: 0,
    mental: 4,
    Fatigue: 80,
    defense: 1,
    offense: 1,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "マリーシア",
    card1: "a.7.セットプレー",
    card2: "d.3.サイン会",
    card3: "/",
    kick: 2,
    speed: 8,
    energy: -2,
    technique: 0,
    physical: 0,
    jump: 0,
    mental: 6,
    Fatigue: 20,
    defense: 0,
    offense: 1,
    type1: "レジスタ(8)",
    type2: "",
    type3: "",
  },
  {
    menu: "マルセイユルーレット",
    card1: "c.5.アジリティ",
    card2: "c.7.ストレッチ",
    card3: "d.a.カルチョビット",
    kick: 0,
    speed: 12,
    energy: 4,
    technique: 4,
    physical: 8,
    jump: 0,
    mental: 4,
    Fatigue: 110,
    defense: 2,
    offense: 2,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ミラクルループ",
    card1: "a.5.ミニゲーム",
    card2: "b.3.シュート",
    card3: "d.2.座禅",
    kick: 7,
    speed: 0,
    energy: 0,
    technique: 2,
    physical: 0,
    jump: 0,
    mental: 8,
    Fatigue: 85,
    defense: 0,
    offense: 4,
    type1: "ダイナモ(6)",
    type2: "",
    type3: "",
  },
  {
    menu: "ムードメーカー",
    card1: "a.1.ビデオ研究",
    card2: "a.5.ミニゲーム",
    card3: "d.b.カラオケ",
    kick: 2,
    speed: 0,
    energy: 4,
    technique: 3,
    physical: 0,
    jump: 0,
    mental: 6,
    Fatigue: 40,
    defense: 1,
    offense: 1,
    type1: "ダイナモ(6)",
    type2: "バランス(8)",
    type3: "",
  },
  {
    menu: "ユーティリティ",
    card1: "a.1.ビデオ研究",
    card2: "c.7.ストレッチ",
    card3: "/",
    kick: 2,
    speed: 4,
    energy: 0,
    technique: 0,
    physical: 4,
    jump: 0,
    mental: 4,
    Fatigue: 73,
    defense: 1,
    offense: 1,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ゆりかごダンス",
    card1: "a.2.マンツーマン",
    card2: "a.5.ミニゲーム",
    card3: "d.1.アロマテラピー",
    kick: 1,
    speed: 0,
    energy: 2,
    technique: 1,
    physical: 2,
    jump: 2,
    mental: 2,
    Fatigue: 50,
    defense: 3,
    offense: 1,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ラッキーボーイ",
    card1: "a.4.カウンター",
    card2: "d.3.サイン会",
    card3: "d.4.PK練習",
    kick: 5,
    speed: 10,
    energy: 0,
    technique: 1,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 45,
    defense: 0,
    offense: 1,
    type1: "レジスタ(4)",
    type2: "ストライカー(6)",
    type3: "",
  },
  {
    menu: "ロケットシュート",
    card1: "b.3.シュート",
    card2: "c.1.ランニング",
    card3: "/",
    kick: 5,
    speed: 6,
    energy: 6,
    technique: 1,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 126,
    defense: 0,
    offense: 4,
    type1: "ダイナモ(8)",
    type2: "",
    type3: "",
  },
  {
    menu: "ロスタイムの奇跡",
    card1: "a.4.カウンター",
    card2: "a.7.セットプレー",
    card3: "d.5.合気道",
    kick: 2,
    speed: 4,
    energy: 0,
    technique: 2,
    physical: 0,
    jump: 0,
    mental: 16,
    Fatigue: 40,
    defense: 0,
    offense: 2,
    type1: "レジスタ(5)",
    type2: "",
    type3: "",
  },
  {
    menu: "ロングスロー",
    card1: "c.2.ウェイト",
    card2: "c.6.エアロビクス",
    card3: "d.8.温泉",
    kick: 0,
    speed: 0,
    energy: 6,
    technique: 4,
    physical: 12,
    jump: 0,
    mental: 4,
    Fatigue: 115,
    defense: 0,
    offense: 0,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "ロングフィード",
    card1: "b.2.プレースキック",
    card2: "c.2.ウェイト",
    card3: "/",
    kick: 8,
    speed: 0,
    energy: 0,
    technique: 0,
    physical: 6,
    jump: 0,
    mental: 4,
    Fatigue: 120,
    defense: 2,
    offense: 1,
    type1: "ストッパー(7)",
    type2: "",
    type3: "",
  },
  {
    menu: "ワイドスペース",
    card1: "a.4.カウンター",
    card2: "a.5.ミニゲーム",
    card3: "/",
    kick: 2,
    speed: 4,
    energy: 4,
    technique: 1,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 66,
    defense: 1,
    offense: 2,
    type1: "レジスタ(5)",
    type2: "",
    type3: "",
  },
  {
    menu: "ワンサイドカット",
    card1: "a.3.プレス",
    card2: "d.6.イメージトレーニング",
    card3: "/",
    kick: 0,
    speed: 3,
    energy: 0,
    technique: 3,
    physical: 0,
    jump: 0,
    mental: 5,
    Fatigue: 53,
    defense: 2,
    offense: 0,
    type1: "バックアップ(5)",
    type2: "",
    type3: "",
  },
  {
    menu: "ワンダーボーイ",
    card1: "a.4.カウンター",
    card2: "d.1.アロマテラピー",
    card3: "d.a.カルチョビット",
    kick: 3,
    speed: 6,
    energy: 0,
    technique: 4,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 30,
    defense: 0,
    offense: 2,
    type1: "レジスタ(10)",
    type2: "",
    type3: "",
  },
  {
    menu: "ワントラップシュート",
    card1: "b.3.シュート",
    card2: "b.5.リフティング",
    card3: "/",
    kick: 6,
    speed: 0,
    energy: 0,
    technique: 5,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 133,
    defense: 0,
    offense: 4,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "稲妻ドリブル",
    card1: "a.5.ミニゲーム",
    card2: "b.1.ドリブル",
    card3: "c.3.キック",
    kick: 2,
    speed: 6,
    energy: 0,
    technique: 6,
    physical: 6,
    jump: 0,
    mental: 0,
    Fatigue: 130,
    defense: 0,
    offense: 5,
    type1: "レジスタ(10)",
    type2: "",
    type3: "",
  },
  {
    menu: "黄金の足/ゴールデンシューズ",
    card1: "a.3.プレス",
    card2: "c.3.キック",
    card3: "d.7.ミーティング",
    kick: 2,
    speed: 2,
    energy: 1,
    technique: 2,
    physical: 4,
    jump: 0,
    mental: 4,
    Fatigue: 75,
    defense: 4,
    offense: 1,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "鬼プレス",
    card1: "a.3.プレス",
    card2: "c.2.ウェイト",
    card3: "d.9.ミニキャンプ",
    kick: 0,
    speed: 6,
    energy: 8,
    technique: 2,
    physical: 0,
    jump: 0,
    mental: 8,
    Fatigue: 90,
    defense: 5,
    offense: 0,
    type1: "ストッパー(4)",
    type2: "",
    type3: "",
  },
  {
    menu: "究極リフレッシュ",
    card1: "c.6.エアロビクス",
    card2: "d.1.アロマテラピー",
    card3: "d.b.カラオケ",
    kick: 0,
    speed: 0,
    energy: 12,
    technique: 2,
    physical: 0,
    jump: 0,
    mental: 8,
    Fatigue: 55,
    defense: 1,
    offense: 1,
    type1: "バックアップ(10)",
    type2: "",
    type3: "",
  },
  {
    menu: "拠点のくさび",
    card1: "a.2.マンツーマン",
    card2: "a.4.カウンター",
    card3: "/",
    kick: 0,
    speed: 2,
    energy: 4,
    technique: 2,
    physical: 4,
    jump: 0,
    mental: 0,
    Fatigue: 53,
    defense: 1,
    offense: 2,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "強烈ミドル",
    card1: "b.3.シュート",
    card2: "c.2.ウェイト",
    card3: "d.3.サイン会",
    kick: 14,
    speed: 0,
    energy: 0,
    technique: 0,
    physical: 4,
    jump: 0,
    mental: 0,
    Fatigue: 105,
    defense: 0,
    offense: 4,
    type1: "ダイナモ(5)",
    type2: "",
    type3: "",
  },
  {
    menu: "空中戦のスペシャリスト",
    card1: "a.7.セットプレー",
    card2: "b.7.ヘディング",
    card3: "c.3.キック",
    kick: 2,
    speed: 0,
    energy: 0,
    technique: 2,
    physical: 6,
    jump: 16,
    mental: 0,
    Fatigue: 110,
    defense: 3,
    offense: 2,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "決起集会",
    card1: "a.2.マンツーマン",
    card2: "d.7.ミーティング",
    card3: "d.b.カラオケ",
    kick: 0,
    speed: 4,
    energy: 4,
    technique: 0,
    physical: 0,
    jump: 4,
    mental: 8,
    Fatigue: 30,
    defense: 4,
    offense: 0,
    type1: "オールラウンド(8)",
    type2: "ストッパー(10)",
    type3: "",
  },
  {
    menu: "決死のブロック",
    card1: "b.6.スライディング",
    card2: "d.2.座禅",
    card3: "/",
    kick: 0,
    speed: 0,
    energy: 0,
    technique: 3,
    physical: 6,
    jump: 0,
    mental: 8,
    Fatigue: 73,
    defense: 2,
    offense: 0,
    type1: "スイーパー(5)",
    type2: "バックアップ(7)",
    type3: "スイーパー(8)",
  },
  {
    menu: "攻撃の要",
    card1: "b.1.ドリブル",
    card2: "d.4.PK練習",
    card3: "/",
    kick: 4,
    speed: 6,
    energy: 2,
    technique: 2,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 93,
    defense: 0,
    offense: 2,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "鋼のボディ",
    card1: "a.1.ビデオ研究",
    card2: "c.2.ウェイト",
    card3: "c.3.キック",
    kick: 4,
    speed: 0,
    energy: 0,
    technique: 3,
    physical: 16,
    jump: 0,
    mental: 0,
    Fatigue: 105,
    defense: 2,
    offense: 2,
    type1: "ストッパー(7)",
    type2: "",
    type3: "",
  },
  {
    menu: "高速ドリブル",
    card1: "b.1.ドリブル",
    card2: "c.4.ダッシュ",
    card3: "/",
    kick: 0,
    speed: 12,
    energy: 4,
    technique: 4,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 133,
    defense: 0,
    offense: 4,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "魂のラストパス",
    card1: "a.4.カウンター",
    card2: "b.4.パス",
    card3: "d.2.座禅",
    kick: 0,
    speed: 6,
    energy: 4,
    technique: 4,
    physical: 0,
    jump: 0,
    mental: 8,
    Fatigue: 75,
    defense: 1,
    offense: 2,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "最後の切り札",
    card1: "a.7.セットプレー",
    card2: "b.4.パス",
    card3: "d.8.温泉",
    kick: 8,
    speed: 8,
    energy: 0,
    technique: 0,
    physical: 6,
    jump: 4,
    mental: 0,
    Fatigue: 75,
    defense: 0,
    offense: 3,
    type1: "レジスタ(4)",
    type2: "ストライカー(9)",
    type3: "",
  },
  {
    menu: "司令塔",
    card1: "a.5.ミニゲーム",
    card2: "d.9.ミニキャンプ",
    card3: "/",
    kick: 2,
    speed: 0,
    energy: 4,
    technique: 2,
    physical: 0,
    jump: 0,
    mental: 6,
    Fatigue: 66,
    defense: 0,
    offense: 2,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "執念のクリア",
    card1: "b.7.ヘディング",
    card2: "c.7.ストレッチ",
    card3: "d.5.合気道",
    kick: 0,
    speed: 6,
    energy: 0,
    technique: 2,
    physical: 4,
    jump: 10,
    mental: 10,
    Fatigue: 110,
    defense: 4,
    offense: 0,
    type1: "バックアップ(9)",
    type2: "",
    type3: "",
  },
  {
    menu: "蹴球プロフェッサー",
    card1: "a.1.ビデオ研究",
    card2: "a.7.セットプレー",
    card3: "d.a.カルチョビット",
    kick: 4,
    speed: 4,
    energy: 0,
    technique: 2,
    physical: 0,
    jump: 0,
    mental: 8,
    Fatigue: 25,
    defense: 1,
    offense: 1,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "仁王立ち",
    card1: "c.3.キック",
    card2: "d.2.座禅",
    card3: "/",
    kick: 0,
    speed: 0,
    energy: 0,
    technique: 4,
    physical: 10,
    jump: 0,
    mental: 4,
    Fatigue: 73,
    defense: 3,
    offense: 0,
    type1: "バックアップ(5)",
    type2: "スイーパー(8)",
    type3: "",
  },
  {
    menu: "数的優位",
    card1: "a.6.ラインコントロール",
    card2: "c.5.アジリティ",
    card3: "/",
    kick: 0,
    speed: 5,
    energy: 5,
    technique: 0,
    physical: 0,
    jump: 4,
    mental: 4,
    Fatigue: 80,
    defense: 4,
    offense: 0,
    type1: "バックアップ(8)",
    type2: "バランス(10)",
    type3: "",
  },
  {
    menu: "声の連携",
    card1: "a.6.ラインコントロール",
    card2: "d.b.カラオケ",
    card3: "/",
    kick: 0,
    speed: 0,
    energy: 4,
    technique: 1,
    physical: 0,
    jump: 0,
    mental: 8,
    Fatigue: 20,
    defense: 3,
    offense: 0,
    type1: "バックアップ(4)",
    type2: "リベロ(8)",
    type3: "",
  },
  {
    menu: "大激怒",
    card1: "a.2.マンツーマン",
    card2: "c.3.キック",
    card3: "c.5.アジリティ",
    kick: 2,
    speed: 0,
    energy: 0,
    technique: 6,
    physical: 8,
    jump: 6,
    mental: 0,
    Fatigue: 120,
    defense: 4,
    offense: 2,
    type1: "オールラウンド(5)",
    type2: "マンマーカー(7)",
    type3: "",
  },
  {
    menu: "卓越キープ力",
    card1: "b.5.リフティング",
    card2: "c.1.ランニング",
    card3: "d.2.座禅",
    kick: 0,
    speed: 6,
    energy: 6,
    technique: 8,
    physical: 0,
    jump: 0,
    mental: 6,
    Fatigue: 100,
    defense: 2,
    offense: 2,
    type1: "ダイナモ(5)",
    type2: "",
    type3: "",
  },
  {
    menu: "中盤のマエストロ",
    card1: "b.2.プレースキック",
    card2: "b.4.パス",
    card3: "c.5.アジリティ",
    kick: 5,
    speed: 8,
    energy: 0,
    technique: 5,
    physical: 0,
    jump: 0,
    mental: 6,
    Fatigue: 140,
    defense: 2,
    offense: 3,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "超ロングシュート",
    card1: "b.3.シュート",
    card2: "c.3.キック",
    card3: "d.a.カルチョビット",
    kick: 8,
    speed: 0,
    energy: 0,
    technique: 1,
    physical: 4,
    jump: 0,
    mental: 4,
    Fatigue: 110,
    defense: 0,
    offense: 4,
    type1: "ストッパー(7)",
    type2: "",
    type3: "",
  },
  {
    menu: "鉄拳制裁",
    card1: "a.2.マンツーマン",
    card2: "c.2.ウェイト",
    card3: "d.5.合気道",
    kick: 5,
    speed: 0,
    energy: 0,
    technique: 0,
    physical: 12,
    jump: 0,
    mental: 6,
    Fatigue: 80,
    defense: 4,
    offense: 0,
    type1: "オールラウンド(5)",
    type2: "マンマーカー(7)",
    type3: "オールラウンド(10)",
  },
  {
    menu: "鉄壁ディフェンス",
    card1: "a.2.マンツーマン",
    card2: "a.3.プレス",
    card3: "/",
    kick: 0,
    speed: 0,
    energy: 5,
    technique: 2,
    physical: 5,
    jump: 0,
    mental: 0,
    Fatigue: 53,
    defense: 4,
    offense: 0,
    type1: "ストッパー(3)",
    type2: "マンマーカー(9)",
    type3: "",
  },
  {
    menu: "伝説のフリーキック",
    card1: "b.2.プレースキック",
    card2: "d.6.イメージトレーニング",
    card3: "d.9.ミニキャンプ",
    kick: 11,
    speed: 0,
    energy: 0,
    technique: 0,
    physical: 0,
    jump: 0,
    mental: 10,
    Fatigue: 80,
    defense: 0,
    offense: 1,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "怒濤の全員攻撃",
    card1: "b.1.ドリブル",
    card2: "b.4.パス",
    card3: "d.3.サイン会",
    kick: 3,
    speed: 10,
    energy: 6,
    technique: 4,
    physical: 0,
    jump: 6,
    mental: 0,
    Fatigue: 105,
    defense: 0,
    offense: 4,
    type1: "レジスタ(8)",
    type2: "",
    type3: "",
  },
  {
    menu: "闘将",
    card1: "c.4.ダッシュ",
    card2: "d.5.合気道",
    card3: "/",
    kick: 2,
    speed: 4,
    energy: 0,
    technique: 3,
    physical: 4,
    jump: 0,
    mental: 4,
    Fatigue: 80,
    defense: 1,
    offense: 1,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "肉体改造",
    card1: "c.2.ウェイト",
    card2: "c.4.ダッシュ",
    card3: "c.7.ストレッチ",
    kick: 5,
    speed: 10,
    energy: 0,
    technique: 0,
    physical: 8,
    jump: 10,
    mental: 0,
    Fatigue: 150,
    defense: 3,
    offense: 3,
    type1: "ストッパー(5)",
    type2: "",
    type3: "",
  },
  {
    menu: "熱血コーチング",
    card1: "a.5.ミニゲーム",
    card2: "a.6.ラインコントロール",
    card3: "d.5.合気道",
    kick: 0,
    speed: 0,
    energy: 6,
    technique: 4,
    physical: 0,
    jump: 0,
    mental: 10,
    Fatigue: 50,
    defense: 3,
    offense: 1,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "波状攻撃",
    card1: "a.5.ミニゲーム",
    card2: "c.1.ランニング",
    card3: "/",
    kick: 2,
    speed: 4,
    energy: 4,
    technique: 2,
    physical: 0,
    jump: 0,
    mental: 4,
    Fatigue: 100,
    defense: 2,
    offense: 2,
    type1: "ダイナモ(3)",
    type2: "",
    type3: "",
  },
  {
    menu: "反転速攻",
    card1: "a.4.カウンター",
    card2: "b.6.スライディング",
    card3: "/",
    kick: 0,
    speed: 6,
    energy: 0,
    technique: 3,
    physical: 3,
    jump: 0,
    mental: 0,
    Fatigue: 93,
    defense: 0,
    offense: 3,
    type1: "レジスタ(9)",
    type2: "",
    type3: "",
  },
  {
    menu: "必殺スライディング",
    card1: "b.6.スライディング",
    card2: "c.3.キック",
    card3: "d.5.合気道",
    kick: 3,
    speed: 0,
    energy: 0,
    technique: 7,
    physical: 10,
    jump: 0,
    mental: 0,
    Fatigue: 110,
    defense: 4,
    offense: 0,
    type1: "ストッパー(5)",
    type2: "マンマーカー(8)",
    type3: "",
  },
  {
    menu: "不屈の闘志",
    card1: "a.3.プレス",
    card2: "d.2.座禅",
    card3: "/",
    kick: 0,
    speed: 0,
    energy: 0,
    technique: 3,
    physical: 0,
    jump: 0,
    mental: 10,
    Fatigue: 33,
    defense: 2,
    offense: 0,
    type1: "ストッパー(7)",
    type2: "",
    type3: "",
  },
  {
    menu: "変幻ドリブラー",
    card1: "b.1.ドリブル",
    card2: "b.5.リフティング",
    card3: "c.6.エアロビクス",
    kick: 0,
    speed: 14,
    energy: 6,
    technique: 7,
    physical: 0,
    jump: 0,
    mental: 0,
    Fatigue: 150,
    defense: 0,
    offense: 5,
    type1: "",
    type2: "",
    type3: "",
  },
  {
    menu: "野人",
    card1: "c.1.ランニング",
    card2: "c.4.ダッシュ",
    card3: "c.6.エアロビクス",
    kick: 0,
    speed: 20,
    energy: 20,
    technique: 0,
    physical: 0,
    jump: 0,
    mental: -2,
    Fatigue: 145,
    defense: 3,
    offense: 3,
    type1: "レジスタ(6)",
    type2: "",
    type3: "",
  },
  {
    menu: "友情のホットライン",
    card1: "b.4.パス",
    card2: "c.6.エアロビクス",
    card3: "d.9.ミニキャンプ",
    kick: 0,
    speed: 6,
    energy: 8,
    technique: 4,
    physical: 2,
    jump: 0,
    mental: 2,
    Fatigue: 120,
    defense: 2,
    offense: 2,
    type1: "",
    type2: "",
    type3: "",
  },
];

export const cardData: cardsType = {
  tactical: [
    {
      key: "a.1",
      name: "ビデオ研究",
      count: 0,
    },
    {
      key: "a.2",
      name: "マンツーマン",
      count: 0,
    },
    {
      key: "a.3",
      name: "プレス",
      count: 0,
    },
    {
      key: "a.4",
      name: "カウンター",
      count: 0,
    },
    {
      key: "a.5",
      name: "ミニゲーム",
      count: 0,
    },
    {
      key: "a.6",
      name: "ラインコントロール",
      count: 0,
    },
    {
      key: "a.7",
      name: "セットプレー",
      count: 0,
    },
  ],
  technical: [
    {
      key: "b.1",
      name: "ドリブル",
      count: 0,
    },
    {
      key: "b.2",
      name: "プレースキック",
      count: 0,
    },
    {
      key: "b.3",
      name: "シュート",
      count: 0,
    },
    {
      key: "b.4",
      name: "パス",
      count: 0,
    },
    {
      key: "b.5",
      name: "リフティング",
      count: 0,
    },
    {
      key: "b.6",
      name: "スライディング",
      count: 0,
    },
    {
      key: "b.7",
      name: "ヘディング",
      count: 0,
    },
  ],
  physical: [
    {
      key: "c.1",
      name: "ランニング",
      count: 0,
    },
    {
      key: "c.2",
      name: "ウェイト",
      count: 0,
    },
    {
      key: "c.3",
      name: "キック",
      count: 0,
    },
    {
      key: "c.4",
      name: "ダッシュ",
      count: 0,
    },
    {
      key: "c.5",
      name: "アジリティ",
      count: 0,
    },
    {
      key: "c.6",
      name: "エアロビクス",
      count: 0,
    },
    {
      key: "c.7",
      name: "ストレッチ",
      count: 0,
    },
  ],
  support: [
    {
      key: "d.1",
      name: "アロマテラピー",
      count: 0,
    },
    {
      key: "d.2",
      name: "座禅",
      count: 0,
    },
    {
      key: "d.3",
      name: "サイン会",
      count: 0,
    },
    {
      key: "d.4",
      name: "PK練習",
      count: 0,
    },
    {
      key: "d.5",
      name: "合気道",
      count: 0,
    },
    {
      key: "d.6",
      name: "イメージトレーニング",
      count: 0,
    },
    {
      key: "d.7",
      name: "ミーティング",
      count: 0,
    },
    {
      key: "d.8",
      name: "温泉",
      count: 0,
    },
    {
      key: "d.9",
      name: "ミニキャンプ",
      count: 0,
    },
    {
      key: "d.a",
      name: "カルチョビット",
      count: 0,
    },
    {
      key: "d.b",
      name: "カラオケ",
      count: 0,
    },
  ],
};
